Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dns/zone.py", line 975, in read
    self._rr_line()
  File "/usr/lib/python3/dist-packages/dns/zone.py", line 694, in _rr_line
    raise dns.exception.SyntaxError("RR class is not zone's class")
dns.exception.SyntaxError: RR class is not zone's class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wessels/Edit/github.com/ZoneDigestHackathon-wessels/digestify.py", line 79, in <module>
    main()
  File "/home/wessels/Edit/github.com/ZoneDigestHackathon-wessels/digestify.py", line 55, in main
    zone = dns.zone.from_file(filename, check_origin=False,
  File "/usr/lib/python3/dist-packages/dns/zone.py", line 1080, in from_file
    z = from_text(f, origin, rdclass, relativize, zone_factory,
  File "/usr/lib/python3/dist-packages/dns/zone.py", line 1028, in from_text
    reader.read()
  File "/usr/lib/python3/dist-packages/dns/zone.py", line 980, in read
    raise dns.exception.SyntaxError(
dns.exception.SyntaxError: zones/80-mixed-classes/example.zone:5: RR class is not zone's class

zone-digest-hackathon.sh exited with status 1
